---

##
# This file is part of `scr-be/teavee-image-magic-bundle`
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

# Set the required project language environment and advise
# Travis that this project fully supports the new, speedy,
# container-built infrastructure.
language : php
sudo     : false

# Build against the following engines: Zend 5.6.x, 7.0.x, and
# 7-nightly, and HHVM-stable and -nightly builds.
php :
  - 5.6
  - 7.0
  - hhvm-nightly

# Define build matrix to allow both HHVM environments to fail,
# as we are only testing it right now. Also, turn on fast-finish
# so results are finalized quickly (prior to allowed-failures
# finishing).
matrix :
  fast_finish    : true
  allow_failures :
    - php : hhvm-nightly

# Set a sane clone depth for Git.
git :
  depth : 3

# List of services to enable. Globally we make sure Memcached and
# MySQL is installed and running.
services :
  - mysql
  - memcached

# Add custom Hostname to build environment and install imagemagick build requirements.
addons :
  hosts :
    - mainline.src.run
  apt :
    packages :
      - binutils
      - build-essential
      - chrpath
      - cpp
      - cpp-4.6
      - dconf-gsettings-backend
      - dconf-service
      - debhelper
      - dh-apparmor
      - dpkg-dev
      - fontconfig
      - fontconfig-config
      - g++
      - g++-4.6
      - gcc
      - gcc-4.6
      - gettext
      - ghostscript
      - gir1.2-atk-1.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-gtk-2.0
      - gir1.2-pango-1.0
      - gir1.2-rsvg-2.0
      - gs-cjk-resource
      - gsfonts
      - html2text
      - intltool-debian
      - libatk1.0-0
      - libatk1.0-data
      - libatk1.0-dev
      - libavahi-client3
      - libavahi-common-data
      - libavahi-common3
      - libbz2-dev
      - libc-dev-bin
      - libc6-dev
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcairo2
      - libcairo2-dev
      - libcdt4
      - libcgraph5
      - libcroco3
      - libcups2
      - libcupsimage2
      - libdatrie1
      - libdconf0
      - libdjvulibre-dev
      - libdjvulibre-text
      - libdjvulibre21
      - libdpkg-perl
      - libexif-dev
      - libexif12
      - libexpat1-dev
      - libfontconfig1
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgd2-noxpm
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libgdk-pixbuf2.0-dev
      - libgettextpo0
      - libglib2.0-bin
      - libglib2.0-data
      - libglib2.0-dev
      - libgomp1
      - libgraph4
      - libgraphviz-dev
      - libgs9
      - libgs9-common
      - libgtk-3-0
      - libgtk-3-common
      - libgtk2.0-0
      - libgtk2.0-common
      - libgtk2.0-dev
      - libgvc5
      - libgvpr1
      - libice-dev
      - libice6
      - libijs-0.35
      - libilmbase-dev
      - libilmbase6
      - libjasper-dev
      - libjasper1
      - libjbig2dec0
      - libjpeg-dev
      - libjpeg-turbo8
      - libjpeg-turbo8-dev
      - libjpeg8
      - libjpeg8-dev
      - liblcms1
      - liblcms1-dev
      - liblcms2-2
      - liblqr-1-0
      - liblqr-1-0-dev
      - libltdl-dev
      - libltdl7
      - libmpc2
      - libmpfr4
      - libopenexr-dev
      - libopenexr6
      - libpango1.0-0
      - libpango1.0-dev
      - libpaper1
      - libpathplan4
      - libpcre3-dev
      - libpcrecpp0
      - libperl-dev
      - libperl5.14
      - libpixman-1-0
      - libpixman-1-dev
      - libpng12-dev
      - libpthread-stubs0
      - libpthread-stubs0-dev
      - libquadmath0
      - librsvg2-2
      - librsvg2-bin
      - librsvg2-common
      - librsvg2-dev
      - libsm-dev
      - libsm6
      - libstdc++6-4.6-dev
      - libthai-data
      - libthai0
      - libtiff4
      - libtiff4-dev
      - libtiffxx0c2
      - libunistring0
      - libwmf-dev
      - libwmf0.2-7
      - libx11-dev
      - libxau-dev
      - libxcb-render0
      - libxcb-render0-dev
      - libxcb-shm0
      - libxcb-shm0-dev
      - libxcb1-dev
      - libxcomposite-dev
      - libxcomposite1
      - libxcursor-dev
      - libxcursor1
      - libxdamage-dev
      - libxdamage1
      - libxdmcp-dev
      - libxdot4
      - libxext-dev
      - libxfixes-dev
      - libxfixes3
      - libxft-dev
      - libxft2
      - libxi-dev
      - libxi6
      - libxinerama-dev
      - libxinerama1
      - libxml2-dev
      - libxml2-utils
      - libxrandr-dev
      - libxrandr2
      - libxrender-dev
      - libxrender1
      - libxt-dev
      - libxt6
      - linux-libc-dev
      - make
      - pkg-config
      - po-debconf
      - shared-mime-info
      - ttf-dejavu-core
      - x11-common
      - x11proto-composite-dev
      - x11proto-core-dev
      - x11proto-damage-dev
      - x11proto-fixes-dev
      - x11proto-input-dev
      - x11proto-kb-dev
      - x11proto-randr-dev
      - x11proto-render-dev
      - x11proto-xext-dev
      - x11proto-xinerama-dev
      - xorg-sgml-doctools
      - xtrans-dev
      - zlib1g-dev

# Define any required global enviornment variables. Specifically,
# the package_builder variable must be set to true to enable the
# automated package builder scripts.
env :
  global :
    - build_package=true

# Use builder to install system environment and application 
# requirements.
install :
  - bash .config/builders/build-reqs/build-reqs.bash up-env
  - bash .config/builders/build-reqs/build-reqs.bash up-app

# Run unit tests!
script : bin/phpunit -vvv

# Use builder to run post-operations, most importantly handle
# statistics submissions for text coverage.
after_script :
  - bash .config/builders/build-reqs/build-reqs.bash dn-app
  - bash .config/builders/build-reqs/build-reqs.bash dn-env

...
